# Generated by Django 4.2.5 on 2025-02-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_email_id',
        ),
    ]
