# Generated by Django 4.2.4 on 2023-09-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_capacity',
        ),
    ]
