# Generated by Django 4.2.4 on 2023-09-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_remove_room_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassign',
            name='food_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=20),
        ),
    ]
