# Generated by Django 4.2.4 on 2023-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_roomassign_food_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomassign',
            name='room_left_date',
        ),
        migrations.AddField(
            model_name='roomassign',
            name='Duration',
            field=models.IntegerField(default=None),
        ),
    ]
