# Generated by Django 4.2.4 on 2023-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_roomassign_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassign',
            name='food_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='4000rs for one month', max_length=20),
        ),
    ]
