# Generated by Django 4.2.4 on 2023-09-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_alter_roomassign_food_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_type', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='roomassign',
            name='total_payment',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='roomassign',
            name='fees_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.fees'),
        ),
    ]
