# Generated by Django 4.2.4 on 2023-09-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_fees_roomassign_total_payment_roomassign_fees_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassign',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Onetimepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('room_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.roomassign')),
            ],
        ),
    ]
