# Generated by Django 4.2.4 on 2023-09-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_alter_roomassign_total_payment_onetimepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassign',
            name='fees_type',
            field=models.ForeignKey(default=None, help_text='hostel fee 4000rs per month ,for recurring payment,there will be 3 installments that you have to pay in each month', on_delete=django.db.models.deletion.CASCADE, to='baseapp.fees'),
        ),
        migrations.AlterField(
            model_name='roomassign',
            name='food_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='2000 rs for one month', max_length=20),
        ),
    ]
