# Generated by Django 4.2.4 on 2023-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_alter_roomassign_fees_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneteambranch',
            options={'verbose_name_plural': 'OneTeam Branches'},
        ),
        migrations.AddField(
            model_name='oneteambranch',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
