# Generated by Django 4.2.5 on 2024-11-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_alter_oneteambranch_options_oneteambranch_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='oneteam_branch_name',
            field=models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='baseapp.oneteambranch'),
        ),
    ]
