# Generated by Django 4.2.5 on 2025-01-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_alter_student_oneteam_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='trainer_name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.course'),
            preserve_default=False,
        ),
    ]
