# Generated by Django 4.2.5 on 2025-01-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_remove_student_trainer_name_trainer_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.oneteambranch'),
            preserve_default=False,
        ),
    ]
