# Generated by Django 4.2.5 on 2025-01-31 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_trainer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.trainer'),
            preserve_default=False,
        ),
    ]
