# Generated by Django 4.2.5 on 2025-02-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_type', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_type', models.CharField(choices=[("Men's Hostel", "Men's Hostel"), ("Women's Hostel", "Women's Hostel")], max_length=30)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.oneteambranch')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default=None, max_length=30)),
                ('room_no', models.IntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=20)),
                ('hostel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.IntegerField(default=None, help_text='In months')),
                ('room_assigned_date', models.DateField(default=None)),
                ('food_required', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='2000 rs for one month', max_length=20)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fees_type', models.ForeignKey(default=None, help_text='hostel fee 4000rs per month ,for recurring payment,there will be 3 installments that you have to pay in each month', on_delete=django.db.models.deletion.CASCADE, to='hostel.fees')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Onetimepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('room_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.roomassign')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.warden'),
        ),
    ]
