# Generated by Django 4.2.5 on 2025-02-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_room_room_name_room_room_alloted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassign',
            name='room_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='hostel.room'),
        ),
    ]
