# Generated by Django 4.2.5 on 2025-02-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_auto_20250205_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomassign',
            name='room_new',
        ),
        migrations.AlterField(
            model_name='roomassign',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='hostel.room'),
        ),
    ]
