# Generated by Django 4.2.5 on 2025-02-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_roomassign_room_new_alter_roomassign_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_type', models.CharField(choices=[('ONE TIME', 'One Time Payment'), ('RECURRING', 'Recurring Payment')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('food_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fees_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel.feesmethod')),
                ('room_assigned', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.roomassign')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=20)),
                ('fee_per_person', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Onetimepayment',
        ),
        migrations.AddField(
            model_name='room',
            name='room_fee',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.roomfeestructure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomassign',
            name='fees_type',
            field=models.ForeignKey(default=None, help_text='hostel fee 4000rs per month ,for recurring payment,there will be 3 installments that you have to pay in each month', on_delete=django.db.models.deletion.CASCADE, to='hostel.feesmethod'),
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
