# Generated by Django 4.2.5 on 2025-02-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_feesmethod_payment_roomfeestructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.roomfeestructure'),
        ),
    ]
