# Generated by Django 4.2.5 on 2025-02-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_room_room_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.roomfeestructure'),
        ),
    ]
