# Generated by Django 4.2.5 on 2025-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_room_room_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_fee',
        ),
    ]
