# Generated by Django 4.2.5 on 2025-02-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_alter_payment_food_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassign',
            name='fees_type',
            field=models.ForeignKey(help_text='hostel fee 4000rs per month ,for recurring payment,there will be 3 installments that you have to pay in each month', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.feesmethod'),
        ),
    ]
